const $=id=>document.getElementById(id);
const SETTINGS_KEY='chatwebllm.settings.v1',CHATS_KEY='chatwebllm.chats.v1';
const defaults={provider:'ollama',baseUrl:'http://127.0.0.1:11434',model:'',apiKey:'',temperature:.7,maxTokens:2048,reasoning:'off',systemPrompt:'You are a helpful assistant.',toolsEnabled:true,calculatorTool:true,timeTool:true,jsTool:false,nerdamerTool:false,jsTimeout:2500,theme:'system'};
let settings={...defaults,...readJSON(SETTINGS_KEY,{})},chats=readJSON(CHATS_KEY,[]),activeId=chats[0]?.id||null,files=[],busy=false;

function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));localStorage.setItem(CHATS_KEY,JSON.stringify(chats))}
function id(){return crypto.randomUUID?.()||Date.now()+'-'+Math.random()}
function active(){return chats.find(c=>c.id===activeId)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function md(s=''){return esc(s).replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
function auth(){return settings.apiKey?{Authorization:`Bearer ${settings.apiKey}`}:{}}
function base(){return settings.baseUrl.replace(/\/+$/,'')}

function applyTheme(){let dark=settings.theme==='dark'||(settings.theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.classList.toggle('dark',dark)}
matchMedia('(prefers-color-scheme:dark)').addEventListener?.('change',()=>settings.theme==='system'&&applyTheme());

function newChat(){const c={id:id(),title:'New conversation',messages:[],created:Date.now()};chats.unshift(c);activeId=c.id;save();render()}
function deleteChat(cid,e){e?.stopPropagation();chats=chats.filter(c=>c.id!==cid);if(activeId===cid)activeId=chats[0]?.id||null;save();render()}
function renderList(){$('chatList').innerHTML=chats.map(c=>`<button data-chat="${c.id}" class="group flex w-full items-center gap-2 rounded-xl px-3 py-2 text-left text-xs ${c.id===activeId?'bg-zinc-200 dark:bg-zinc-800':'hover:bg-zinc-200 dark:hover:bg-zinc-800'}"><span class="min-w-0 flex-1 truncate">${esc(c.title)}</span><span data-del="${c.id}" class="hidden text-zinc-500 group-hover:inline">×</span></button>`).join('');document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>{activeId=b.dataset.chat;render()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=e=>deleteChat(b.dataset.del,e))}
function renderMessages(){const c=active();$('modelLabel').textContent=settings.model||'No model selected';$('chatTitle').textContent=c?.title||'New conversation';if(!c||!c.messages.length){$('welcome').classList.remove('hidden');$('messages').classList.add('hidden');$('messages').innerHTML='';return}$('welcome').classList.add('hidden');$('messages').classList.remove('hidden');$('messages').innerHTML=c.messages.filter(m=>m.role!=='tool').map(m=>`<div class="flex gap-3 ${m.role==='user'?'justify-end':''}"><div class="max-w-[90%] ${m.role==='user'?'rounded-2xl bg-zinc-100 px-4 py-3 dark:bg-zinc-900':'w-full'}"><div class="mb-1 text-[10px] font-medium uppercase tracking-wide text-zinc-500">${m.role==='user'?'You':'Assistant'}</div><div class="msg text-sm leading-7">${md(m.content||'')}</div></div></div>`).join('');$('chatArea').scrollTop=$('chatArea').scrollHeight}
function renderFiles(){$('attachments').innerHTML=files.map((f,i)=>`<span class="rounded-xl border border-zinc-200 bg-white px-3 py-1.5 text-[11px] dark:border-zinc-800 dark:bg-zinc-900">${esc(f.name)} <button data-file="${i}" class="ml-1 text-zinc-500">×</button></span>`).join('');document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>{files.splice(+b.dataset.file,1);renderFiles()})}
function toolDefs(){if(!settings.toolsEnabled)return[];const t=[];if(settings.calculatorTool)t.push({type:'function',function:{name:'calculator',description:'Evaluate a basic arithmetic expression.',parameters:{type:'object',properties:{expression:{type:'string'}},required:['expression']}}});if(settings.timeTool)t.push({type:'function',function:{name:'current_time',description:'Get the user browser current local date and time.',parameters:{type:'object',properties:{},additionalProperties:false}}});if(settings.jsTool)t.push({type:'function',function:{name:'run_javascript',description:`Run JavaScript in an isolated browser sandbox. ${settings.nerdamerTool?'Nerdamer is preloaded as global nerdamer for symbolic math.':''}`,parameters:{type:'object',properties:{code:{type:'string',description:'JavaScript code. Return a JSON-serializable value.'}},required:['code']}}});return t}
function renderToolCount(){const n=toolDefs().length;$('toolCount').textContent=n?`${n} tool${n===1?'':'s'} enabled`:''}
function render(){if(!activeId&&chats.length)activeId=chats[0].id;renderList();renderMessages();renderFiles();renderToolCount();applyTheme()}

function loadForm(){for(const k of ['provider','baseUrl','model','apiKey','temperature','maxTokens','reasoning','systemPrompt','jsTimeout','theme'])$(k).value=settings[k];for(const k of ['toolsEnabled','calculatorTool','timeTool','jsTool','nerdamerTool'])$(k).checked=!!settings[k]}
function saveForm(){for(const k of ['provider','baseUrl','model','apiKey','reasoning','systemPrompt','theme'])settings[k]=$(k).value;settings.temperature=+$('temperature').value||0;settings.maxTokens=+$('maxTokens').value||2048;settings.jsTimeout=Math.max(250,Math.min(10000,+$('jsTimeout').value||2500));for(const k of ['toolsEnabled','calculatorTool','timeTool','jsTool','nerdamerTool'])settings[k]=$(k).checked;if(!settings.jsTool)settings.nerdamerTool=false;save();applyTheme();render();closeSettings()}
function openSettings(){loadForm();$('settings').classList.remove('hidden');$('settings').classList.add('flex')}
function closeSettings(){$('settings').classList.add('hidden');$('settings').classList.remove('flex')}

async function listModels(){const out=$('modelChoices');out.innerHTML='';$('testResult').textContent='Loading…';try{let names;if($('provider').value==='ollama'){const r=await fetch($('baseUrl').value.replace(/\/+$/,'')+'/api/tags');if(!r.ok)throw Error(await r.text());names=(await r.json()).models?.map(x=>x.name)||[]}else{const r=await fetch($('baseUrl').value.replace(/\/+$/,'')+'/v1/models',{headers:$('apiKey').value?{Authorization:`Bearer ${$('apiKey').value}`}:{}});if(!r.ok)throw Error(await r.text());names=(await r.json()).data?.map(x=>x.id)||[]}out.innerHTML=names.map(n=>`<button data-model-choice="${esc(n)}" class="rounded-lg border border-zinc-300 px-2 py-1 text-[11px] dark:border-zinc-700">${esc(n)}</button>`).join('');document.querySelectorAll('[data-model-choice]').forEach(b=>b.onclick=()=>{$('model').value=b.dataset.modelChoice});$('testResult').textContent=`${names.length} model(s)`}catch(e){$('testResult').textContent='Failed: '+e.message}}
async function testConnection(){try{await listModels();$('testResult').textContent='Connected';$('statusDot').className='text-green-500';$('statusText').textContent='Connected'}catch(e){$('testResult').textContent='Failed: '+e.message}}

function fileContext(){if(!files.length)return'';return '\n\nAttached files:\n'+files.map(f=>`--- ${f.name} ---\n${f.text}`).join('\n')}
async function addFiles(list){for(const f of list){if(f.size>1024*1024){alert(`${f.name} is over 1 MB`);continue}files.push({name:f.name,text:await f.text()})}renderFiles()}

async function send(){if(busy)return;let text=$('prompt').value.trim();if(!text)return;if(!settings.model){openSettings();return}if(!active())newChat();const c=active();const user={role:'user',content:text+fileContext()};c.messages.push(user);if(c.messages.length===1)c.title=text.slice(0,44);$('prompt').value='';files=[];busy=true;$('send').disabled=true;save();render();try{await complete(c)}catch(e){c.messages.push({role:'assistant',content:`Error: ${e.message}`})}finally{busy=false;$('send').disabled=false;save();render()}}

async function complete(c){const tools=toolDefs();if(tools.length)return toolLoop(c,tools);return settings.provider==='ollama'?streamOllama(c):streamOpenAI(c)}
function messagesForApi(c){const m=[];if(settings.systemPrompt)m.push({role:'system',content:settings.systemPrompt});m.push(...c.messages.map(x=>x.tool_calls?x:{role:x.role,content:x.content,tool_call_id:x.tool_call_id}));return m}

async function streamOllama(c){const a={role:'assistant',content:''};c.messages.push(a);render();const body={model:settings.model,messages:messagesForApi({...c,messages:c.messages.slice(0,-1)}).filter(m=>m.role!=='system'||m.content),stream:true,options:{temperature:settings.temperature,num_predict:settings.maxTokens}};if(settings.reasoning!=='off')body.think=settings.reasoning;const r=await fetch(base()+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json',...auth()},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(true){const {done,value}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});let lines=buf.split('\n');buf=lines.pop();for(const line of lines){if(!line.trim())continue;const j=JSON.parse(line);a.content+=j.message?.content||'';renderMessages()}}}
async function streamOpenAI(c){const a={role:'assistant',content:''};c.messages.push(a);render();const body={model:settings.model,messages:messagesForApi({...c,messages:c.messages.slice(0,-1)}),stream:true,temperature:settings.temperature,max_tokens:settings.maxTokens};if(settings.reasoning!=='off')body.reasoning_effort=settings.reasoning;const r=await fetch(base()+'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',...auth()},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(true){const {done,value}=await reader.read();if(done)break;buf+=dec.decode(value,{stream:true});let lines=buf.split('\n');buf=lines.pop();for(let line of lines){line=line.trim();if(!line.startsWith('data:'))continue;const d=line.slice(5).trim();if(d==='[DONE]')return;const j=JSON.parse(d);a.content+=j.choices?.[0]?.delta?.content||'';renderMessages()}}}

async function toolLoop(c,tools){for(let round=0;round<8;round++){const res=settings.provider==='ollama'?await nonstreamOllama(c,tools):await nonstreamOpenAI(c,tools);const calls=res.tool_calls||res.toolCalls||[];if(!calls.length){c.messages.push({role:'assistant',content:res.content||''});return}const assistant={role:'assistant',content:res.content||'',tool_calls:calls.map((x,i)=>normalizeCall(x,i))};c.messages.push(assistant);for(const call of assistant.tool_calls){let args={};try{args=typeof call.function.arguments==='string'?JSON.parse(call.function.arguments||'{}'):call.function.arguments||{}}catch{}const result=await executeTool(call.function.name,args);c.messages.push({role:'tool',tool_call_id:call.id,name:call.function.name,content:JSON.stringify(result)})}save();renderMessages()}throw Error('Tool-call limit reached')}
function normalizeCall(x,i){const f=x.function||x;return{id:x.id||`call_${Date.now()}_${i}`,type:'function',function:{name:f.name,arguments:typeof f.arguments==='string'?f.arguments:JSON.stringify(f.arguments||{})}}}
async function nonstreamOpenAI(c,tools){const body={model:settings.model,messages:messagesForApi(c),tools,tool_choice:'auto',stream:false,temperature:settings.temperature,max_tokens:settings.maxTokens};if(settings.reasoning!=='off')body.reasoning_effort=settings.reasoning;const r=await fetch(base()+'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',...auth()},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());const m=(await r.json()).choices?.[0]?.message||{};return{content:m.content||'',tool_calls:m.tool_calls||[]}}
async function nonstreamOllama(c,tools){const body={model:settings.model,messages:messagesForApi(c).map(m=>m.role==='tool'?{role:'tool',content:m.content}:m),tools,stream:false,options:{temperature:settings.temperature,num_predict:settings.maxTokens}};if(settings.reasoning!=='off')body.think=settings.reasoning;const r=await fetch(base()+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json',...auth()},body:JSON.stringify(body)});if(!r.ok)throw Error(await r.text());const m=(await r.json()).message||{};return{content:m.content||'',tool_calls:m.tool_calls||[]}}

async function executeTool(name,args){if(name==='calculator')return calculator(args.expression);if(name==='current_time')return{iso:new Date().toISOString(),local:new Date().toString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone};if(name==='run_javascript')return runJavascript(args.code||'');return{error:'Unknown tool'}}
function calculator(expr=''){if(!/^[0-9+\-*/%().\s**]+$/.test(expr))return{error:'Only basic arithmetic is allowed'};try{return{result:Function(`"use strict";return (${expr})`)()}}catch(e){return{error:e.message}}}

function runJavascript(code){return new Promise((resolve)=>{const token=id(),timeout=settings.jsTimeout,nerdamer=settings.nerdamerTool;const frame=document.createElement('iframe');frame.sandbox='allow-scripts';frame.style.display='none';document.body.appendChild(frame);const src=`<!doctype html><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' https://cdn.jsdelivr.net blob:; worker-src blob:; connect-src 'none'; img-src 'none'; style-src 'none'"><script>const TOKEN=${JSON.stringify(token)},LIMIT=${timeout},NERD=${nerdamer};addEventListener('message',e=>{if(e.data?.token!==TOKEN)return;const workerCode=\`self.fetch=undefined;self.XMLHttpRequest=undefined;self.WebSocket=undefined;self.EventSource=undefined;let logs=[];console={log:(...a)=>logs.push(a),error:(...a)=>logs.push(a),warn:(...a)=>logs.push(a)};onmessage=async e=>{try{if(e.data.nerd)importScripts('https://cdn.jsdelivr.net/npm/nerdamer@1.1.13/all.min.js');let fn=new Function('return (async()=>{'+e.data.code+'\\n})()');let value=await fn();postMessage({ok:true,value,logs})}catch(err){postMessage({ok:false,error:String(err?.stack||err),logs})}}\`;const blob=new Blob([workerCode],{type:'text/javascript'}),w=new Worker(URL.createObjectURL(blob));const timer=setTimeout(()=>{w.terminate();parent.postMessage({token:TOKEN,result:{ok:false,error:'Sandbox timeout after '+LIMIT+' ms'}},'*')},LIMIT);w.onmessage=x=>{clearTimeout(timer);w.terminate();parent.postMessage({token:TOKEN,result:x.data},'*')};w.onerror=x=>{clearTimeout(timer);w.terminate();parent.postMessage({token:TOKEN,result:{ok:false,error:x.message}},'*')};w.postMessage({code:e.data.code,nerd:NERD})});parent.postMessage({token:TOKEN,ready:true},'*')<\/script>`;let done=false;const cleanup=()=>{if(done)return;done=true;removeEventListener('message',onmsg);frame.remove()};const outer=setTimeout(()=>{cleanup();resolve({ok:false,error:`Sandbox timeout after ${timeout} ms`})},timeout+1000);function onmsg(e){if(e.data?.token!==token)return;if(e.data.ready){frame.contentWindow.postMessage({token,code},'*')}else if(e.data.result){clearTimeout(outer);cleanup();resolve(e.data.result)}}addEventListener('message',onmsg);frame.srcdoc=src})}

$('newChat').onclick=newChat;$('clearChat').onclick=()=>{if(active()){active().messages=[];save();render()}};$('openSettings').onclick=openSettings;$('modelButton').onclick=openSettings;$('closeSettings').onclick=closeSettings;$('saveSettings').onclick=saveForm;$('loadModels').onclick=listModels;$('testConnection').onclick=testConnection;$('send').onclick=send;$('fileInput').onchange=e=>addFiles([...e.target.files]);$('prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('openSidebar').onclick=()=>$('sidebar').classList.add('open');$('closeSidebar').onclick=()=>$('sidebar').classList.remove('open');$('settings').onclick=e=>{if(e.target===$('settings'))closeSettings()};$('jsTool').onchange=()=>{$('nerdamerTool').disabled=!$('jsTool').checked;if(!$('jsTool').checked)$('nerdamerTool').checked=false};
if(!chats.length)newChat();else render();
